name: Our Living Circle
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#99c449'
    - '#89ac46'
    - '#ffffff'
    - '#99c448'
    - '#9ec651'
  brandStrength: 0.8813147735781968
  lightness: 0.3075308764819056
  saturation: 0.6616532728075981
  rhythmicContrast: 0.4456425001844764
purpose: []
