name: Our Living Circle
favicon: null
layout_spectrum: 0.0470683912280947
typography_spectrum: 0.9980907388962805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8813147735781968
  lightness: 0.3075308764819056
  saturation: 0.6616532728075981
  rhythmicContrast: 0.4456425001844764
purpose: []
